openwrt/video

libs/libdouble-conversion/Makefile

Signed-off-by: Yaroslav Petrov <petrov@adg-dresden.de>

libdouble-conversion: move package here from packages-abandoned feed

---

frameworks/wayland-protocols/Makefile
frameworks/wayland/Makefile
frameworks/wayland/patches/001-fix-wayland-scanner-detect.patch
libs/mesa/Makefile
libs/mesa/patches/001-fix-wayland-scanner-detect.patch

* build vulkan drivers only if selected
* disable broadcom vulkan driver as it causes meson-related
build troubles (unrelated to the version bump)
Signed-off-by: Daniel Golle <daniel@makrotopia.org>

mesa: update to version 21.3.0

---

frameworks/wayland/Makefile

As described in https://github.com/openwrt/packages/commit/5bf74f2ad434841bfe9c3013e55556c0005e74cb, packages that supposedly use `expat/host` actually use `tools/expat`.
Signed-off-by: Jeffery To <jeffery.to@gmail.com>

wayland: Use tools/expat instead of expat/host

---

frameworks/qt5base/Makefile
libs/libdouble-conversion/Makefile

This refactors packages to use the new PKG_BUILD_FLAGS feature added to the main repo.

treewide: refactor to use PKG_BUILD_FLAGS

---

games/sdl2-doom/Makefile
libs/sdl2-mixer/Makefile
libs/sdl2/Makefile
libs/sdl2/patches/100-fix-segfault-in-Wayland_DestroyWindow.patch

Add everything needed for a classic DOOM experience.
Note that the patch for SDL fixes a segfault issue which has been addressed upstream by libsdl-org/SDL@68d2d9f76d, however the commit is not atomic and only part of the upcoming SDL3 preview.
Required PRs to be merged before:
* https://github.com/openwrt/packages/pull/25272
* https://github.com/openwrt/packages/pull/25273
* https://github.com/openwrt/packages/pull/25274
* https://github.com/openwrt/video/pull/35

add SDL2, SDL2_mixer and sdl2-doom

---

frameworks/cage/Makefile
frameworks/cage/files/cage.config
frameworks/cage/files/cage.init
frameworks/wlroots/Makefile
games/gzdoom/Makefile
games/gzdoom/patches/0002-fix-musl-fts.patch
games/gzdoom/patches/0003-define-cpu_set_t.patch
games/gzdoom/patches/100-openwrt-cross-build.patch
games/gzdoom/patches/120-lzma-pthreads.patch
games/gzdoom/patches/no-execinfo.patch
games/zmusic/Makefile
libs/cog/Makefile
libs/libwpe/Makefile
libs/wpebackend-fdo/Makefile
libs/wpewebkit/Makefile
libs/wpewebkit/patches/100-fix-compile-with-ICU76.patch
libs/wpewebkit/patches/110-fix-gstreamer-id-tracking.patch

Requires
* https://github.com/openwrt/video/pull/35
* https://github.com/openwrt/packages/pull/25322
* https://github.com/openwrt/packages/pull/25300
* https://github.com/openwrt/packages/pull/25341
* https://github.com/openwrt/packages/pull/25342
* https://github.com/openwrt/packages/pull/25343
* https://github.com/openwrt/packages/pull/25344
See also https://wpewebkit.org

add WPE WebKit packages

---

libs/assimp/Makefile

Use minizip-ng from packages feed instead of building in-tree version of minizip.

assimp: depend on minizip

---

games/zmusic/patches/100-fix-endian-detect-with-musl.patch

Use `__BYTE_ORDER` macro when ever it is defined and not just when using glibc.

zmusic: fix target endian detection

---

libs/sdl2/patches/110-tests-no-libunwind.patch

SDL2 links tests against libunwind if libunwind is detected by CMake. This results in build failure due to undefined symbols. Prevent building with libunwind for now.

sdl2: build without libunwind

---

frameworks/gtk/patches/001-gtkcssnumbervalue-Don-t-use-fesetround-on-softfloat.patch

Use work-around for missing fesetround() options on targets without floating point unit.

gtk: import patch to support softfloat targets

---

games/gzdoom/Makefile
games/gzdoom/patches/120-lzma-pthreads.patch

Install host-built binaries to STAGING_DIR_HOSTPKG as HOST_BUILD_DIR gets cleared and should not be referenced after host build has completed.

gzdoom: stage host binaries

---

libs/sdl2/patches/110-tests-no-libunwind.patch

Previous attempts to prevent linking against libunwind were incomplete. Simply don't call CheckLibUnwind macro.

sdl2: get rid of libunwind for good

---

libs/mesa/Makefile

Define all `CONFIG_PACKAGE_*` symbols which may change build configuration and only build broadcom drivers on ARM targets with FPU.

mesa: clean up dependencies

---

libs/mesa/Makefile

Clover only implements OpenCL API for nouveau, r600 and radeon-si GPUs. Remove OpenCL library packages for targets which anyway implement 0% of the API and are hence useless.
See also https://mesamatrix.net

mesa: remove useless OpenCL libraries

---

libs/wpewebkit/Makefile
libs/wpewebkit/patches/120-PlatformCPU.h-fix-detection-of-PPC-CPU.patch
libs/wpewebkit/patches/121-currentStackPointer-for-Linux-PPC-Linux-PPC64.patch
libs/wpewebkit/patches/122-fix-arm-thumb2-detection.patch

* Use JavaScript JIT only on supported platforms.
* Fix ARM Thumb2 detection to allow using JavaScript JIT on ARMv7.
* Add inline assembly implementation returning the current stack pointer on PPC64 (or PPC).

wpewebkit: portability fixes

---

libs/mesa/Makefile
libs/mesa/patches/100-use-llvm-subproject-vars.patch

Include libs in /usr/lib/gbm/dri_gbm.so as well as /usr/lib/dri/*.so in libmesa packages.

mesa: update to version 24.3.1

---

libs/xkeyboard-config/Makefile

Remove intltool/host dependency. Not needed.

xkeyboard-config: update to 2.44

---

libs/mesa/Makefile

mesa-clc set to 'system' requires the system tool 'mesa-clc' which gets built as part of the mesa/host build.
The mesa/host build however depends on LLVM and others - hence we're trying to avoid pulling in that dependency tree where possible for certain target configurations.
meson option 'mesa-clc' allows for 3 options: enabled, system, auto.
While 'auto' sounds like it will only automagically go for either 'enabled' or 'system', it will also disable CLC support entirely, if only drivers are enabled which don't need it (resulting in `with_clc=false`) - which is exactly what we want.

mesa: setting meson opt mesa-clc to 'auto' if LLVM support disabled

---

libs/libxkbcommon/patches/100-no-python.patch

Unfortunately there is no way to disable running the Python/Jinja2-based tests, so patch mesion.build in order to not fail in case of Python dependency problems on the host.

libxkbcommon: never run Python-based tests

---

libs/libxkbcommon/Makefile
libs/xkeyboard-config/Makefile

/usr/share/X11/xkb should point to ../xkeyboard-config-2 Remove the stray extra '../' to fix the symlink.
Fixes: 7873464 ("libxkbcommon: update to 1.10.0")

libxkbcommon: fix broken symlink
